const P={Gemini:{model:'gemini-2.5-flash',key:'gemini',kind:'gemini'},Groq:{model:'openai/gpt-oss-120b',key:'groq',url:'https://api.groq.com/openai/v1/chat/completions'},OpenRouter:{model:'openrouter/free',key:'openrouter',url:'https://openrouter.ai/api/v1/chat/completions'},Cerebras:{model:'llama-3.3-70b',key:'cerebras',url:'https://api.cerebras.ai/v1/chat/completions'},Mistral:{model:'mistral-small-latest',key:'mistral',url:'https://api.mistral.ai/v1/chat/completions'},'Together AI':{model:'meta-llama/Llama-3.3-70B-Instruct-Turbo',key:'together',url:'https://api.together.xyz/v1/chat/completions'},SambaNova:{model:'Meta-Llama-3.1-70B-Instruct',key:'sambanova',url:'https://api.sambanova.ai/v1/chat/completions'}};
const $=id=>document.getElementById(id), chat=$('chat'), provider=$('provider'), model=$('model'), prompt=$('prompt'), status=$('status'), fallback=$('fallback');
function add(role,text,label){const d=document.createElement('div');d.className='msg '+role;d.innerHTML=`<div class="meta">${label}</div>${esc(text)}`;chat.appendChild(d);chat.scrollTop=chat.scrollHeight} function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(k){return localStorage.getItem('multiai_'+k)||''} function setKey(k,v){v?localStorage.setItem('multiai_'+k,v):localStorage.removeItem('multiai_'+k)}
function openSettings(){const box=$('keys');box.innerHTML='';Object.entries(P).forEach(([name,x])=>{const r=document.createElement('div');r.className='keyrow';r.innerHTML=`<label>${name}</label><input type="password" data-key="${x.key}" value="${esc(key(x.key))}" placeholder="API key">`;box.appendChild(r)});box.querySelectorAll('input').forEach(i=>i.onchange=()=>setKey(i.dataset.key,i.value.trim()));$('settings').showModal()}
$('settingsBtn').onclick=openSettings;$('closeSettings').onclick=()=>$('settings').close();provider.onchange=()=>{const p=provider.value;model.value=P[p]?.model||''};provider.dispatchEvent(new Event('change'));
async function ask(name,q,m){const x=P[name],k=key(x.key);if(!k)throw Error('No API key configured for '+name);if(x.kind==='gemini'){const u=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m||x.model)}:generateContent?key=${encodeURIComponent(k)}`;const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:q}]}]})});const j=await r.json();if(!r.ok)throw Error('HTTP '+r.status+': '+(j.error?.message||'Gemini error'));return j.candidates?.[0]?.content?.parts?.[0]?.text||JSON.stringify(j)}const r=await fetch(x.url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+k},body:JSON.stringify({model:m||x.model,messages:[{role:'user',content:q}],temperature:.7})});const j=await r.json();if(!r.ok)throw Error('HTTP '+r.status+': '+(j.error?.message||'Provider error'));return j.choices?.[0]?.message?.content||JSON.stringify(j)}
async function run(q){let n=provider.value;if(n!=='Auto')return [n,await ask(n,q,model.value.trim())];const names=Object.keys(P);let errors=[];for(const x of names){if(!key(P[x].key))continue;try{return [x,await ask(x,q,P[x].model)]}catch(e){errors.push(x+': '+e.message);if(!fallback.checked)break}}throw Error(errors.length?errors.join('\n'):'No provider API keys configured. Open ⚙️ to add one.')}
$('composer').onsubmit=async e=>{e.preventDefault();const q=prompt.value.trim();if(!q)return;add('user',q,'You');prompt.value='';status.textContent='Sending…';try{const [n,a]=await run(q);add('ai',a,n);status.textContent='Completed with '+n}catch(e){status.textContent=e.message}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
